/**
 * 
 */
package com.flipkart.dao;

import java.util.List;

import com.flipkart.bean.Course;
import com.flipkart.bean.Notification;
import com.flipkart.bean.StudentGrade;
import com.flipkart.constant.ModeOfPayment;
import com.flipkart.exception.CourseLimitExceedException;
import com.flipkart.exception.CourseNotFoundException;
import com.flipkart.exception.SeatNotAvailableException;

/**
 * @author JDI-03
 * Interface for Registration DAO Operation
 *
 */
public interface RegistrationDaoInterface {
	
	/**
	 * Method to register course in database, throws exception if  course not found.
	 * @param studentId
	 * @param clist
	 * @return
	 * @throws CourseNotFoundException
	 * @throws SeatNotAvailableException 
	 * @throws CourseLimitExceedException 
	 */
	public boolean  registerCourses(int studentId,List<String>clist) throws CourseNotFoundException, CourseLimitExceedException, SeatNotAvailableException;
	/**
	 * Method to add course in database
	 * @param courseCode
	 * @param studentId
	 * @return
	 * @throws CourseNotFoundException
	 */
	public boolean addCourse(String courseCode, int studentId) throws CourseNotFoundException, CourseLimitExceedException, SeatNotAvailableException;
	/**
	 * Drop Course selected by student
	 * @param courseCode
	 * @param studentId
	 * @return
	 * @throws CourseNotFoundException 
	 */
	public boolean dropCourse(String courseCode, int studentId) throws CourseNotFoundException;
	/**
	 * Method to get the list of courses available from course catalog 
	 * @param studentId
	 * @return
	 */
	public List<Course> viewCourses(int studentId);
	/**
	 * 
	 * @param studentId
	 * @return
	 */
	public List<Course> viewRegisteredCourses(int studentId);
	/**
	 * Method to view grade card of the student
	 * @param studentId
	 * @return
	 */
	public List<StudentGrade> viewGradeCard(int studentId);
	/**
	 * Method to retrieve fee for the selected courses from the database and calculate total fee
	 * @param studentId
	 * @return
	 */
	public double calculateFee(int studentId);
	/**
	 * Check if seat is available for that particular course
	 * @param courseCode
	 * @return
	 */
	public boolean seatAvailable(String courseCode);
	
	/**Method to get the list of courses registered by the student
	 * Number of registered courses for a student
	 * @param studentId
	 * @return
	 */
	public int numOfRegisteredCourses(int studentId);
	
	/**
	 *  Method for fee payment and send notification to client. The transaction id for the session is generated by UUID.
	 * @param studentId
	 * @param mode
	 * @param amount
	 * @return 
	 */
	Notification payFee(int studentId, ModeOfPayment mode, double amount);
}
